name: Deploy documentation

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-docs.yml'
      - 'apps/docs/**'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up repository
        uses: ./.github/actions/setup-repository

      - name: Check documentation
        run: vp run docs-check

      - name: Build and upload documentation
        uses: withastro/action@e84f40bd8d2caa9e768ec82ad30dd81f0b280853 # v6
        with:
          package-manager: pnpm@11.24.0
          path: ./apps/docs

  deploy:
    name: Deploy documentation
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
